import Head from "next/head";
import { BsFillMoonStarsFill, BsMoonStarsFill } from "react-icons/bs";
import { AiFillMail, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import { useState } from "react";
import Typewriter from "typewriter-effect";
import reactIcon from "../public/assets/react.png";
import jsIcon from "../public/assets/javascript.png";
import cssIcon from "../public/assets/css.png";
import tailwindIcon from "../public/assets/tailwind.png";
import htmlIcon from "../public/assets/html.png";
import firestore from "../public/assets/firestore.png";
import nodeIcon from "../public/assets/node.png";
import nextjsIcon from "../public/assets/nextjs.png";
import AltaBooking from "../public/assets/AltaBooking.png";
import SkFinance from "../public/assets/SkFinance.png";
import UpCapita from "../public/assets/UpCapita.png";
import WhiteOak from "../public/assets/WhiteOak.png";
import itcAMS from "../public/assets/ITC-AMS.png";
import IndusIndBank from "../public/assets/IndusIndBank.png";
import CryptoTracker from "../public/assets/Crypto-Tracker.png";
import ChatApp from "../public/assets/Chat-App.png";
import subrataImage from "../public/assets/subrataImage.jpg";
import { motion } from "framer-motion";
import { FaHome } from "react-icons/fa";
import { FaTools } from "react-icons/fa";
import { BsFillRocketTakeoffFill } from "react-icons/bs";
import { Link } from "react-scroll";

export const fadeIn = (direction, delay) => {
  return {
    hidden: {
      y: direction === "up" ? 80 : direction === "down" ? -80 : 0,
      opacity: 0,
      x: direction === "left" ? 80 : direction === "right" ? -80 : 0,
    },
    show: {
      y: 0,
      x: 0,
      opacity: 1,
      transition: {
        type: "tween",
        duration: 1.2,
        delay: delay,
        ease: [0.25, 0.25, 0.25, 0.75],
      },
    },
  };
};

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      {console.log("state---", darkMode)}
      <Head>
        <title>Subrata Das Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20  lg:px-32 dark:bg-black">
        {/* section-1 */}
        <section id="home" className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              developed by me
            </h1>
            <ul className="flex items-center">
              <li onClick={() => setDarkMode(!darkMode)}>
                <BsMoonStarsFill className="cursor-pointer text-xl dark:text-white " />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-red-600 to-red-800 text-white px-4 py-2 rounded ml-8"
                  href="https://drive.google.com/file/d/1rtSNnqJmuM9ubikBwSHrwp2_iJ1IBiyU/view?usp=sharing"
                  download="Resume"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-red-700 font-medium md:text-6xl">
              Subrata Das
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              <Typewriter
                options={{
                  strings: [
                    "I am a Frontend developer 👨‍💻",
                    "I love❤️ to build things",
                    "I believe in Minimalism ☮",
                  ],

                  autoStart: true,
                  loop: true,
                  deleteSpeed: 20,
                }}
              />
            </h3>
            {/* <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Frontend Engineer</h3> */}
            <p className="text-md py-5 leading-8 text-gray-800 max-w-xl mx-auto dark:text-gray-400">
              {`Hello, I am a experienced React.js frontend engineer specializing
              in Finance and banking projects. I develop highly scalable and
              reusable component-based applications for optimized and fast
              loading. Join me down below and let's ,`}
              <br />
              <strong className="text-gray-500 max-w-xl mx-auto dark:text-gray-500">
                change the world for the better with one new line of code at a
                time!!✨
              </strong>
              {/* Hello I'm a Frontend developer providing services for programming
              and design content needs. Join me down below and let's get
              cracking! */}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600  dark:text-gray-300">
            <a href="mailto:dasbro9@gmail.com" target="_blank">
              <AiFillMail />
            </a>
            <a
              href="https://www.linkedin.com/in/subrata-das-77a6b91b1/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/Subrata-99" target="_blank">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-red-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96">
            <Image
              src={subrataImage}
              alt="subrata_icon"
            // layout="fill"
            // objectFit="cover"
            />
          </div>
        </section>
        {/* section-2 */}
        <section id="skill">
          <div>
            <h3 className="text-3xl font-burtons py-1 dark:text-white">
              Skills{" "}
            </h3>
          </div>
          <div className="my-10 flex flex-wrap lg:flex gap-5 lg:justify-center">
            <div
              title="React"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1  my-5 py-4 text-center flex flex-col items-center   shadow-lg rounded-xl  dark:shadow-blue-300"
            >
              <Image
                className="my-4"
                src={reactIcon}
                alt="reacticon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="Javascript"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-yellow-300"
            >
              <Image
                className="my-4 rounded-xl"
                src={jsIcon}
                alt="jsIcon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="Nodejs"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-green-700"
            >
              <Image
                className="my-4 rounded-xl"
                src={nodeIcon}
                alt="nodeIcon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="Nextjs"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-blue-100"
            >
              <Image
                className="my-4 rounded-xl"
                src={nextjsIcon}
                alt="nextjsIcon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="HTML5"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-orange-400"
            >
              <Image
                className="my-4"
                src={htmlIcon}
                alt="htmlIcon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="CSS3"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-blue-400"
            >
              <Image
                className="my-4"
                src={cssIcon}
                alt="cssIcon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="Tailwind"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-red-300"
            >
              <Image
                className="my-4"
                src={tailwindIcon}
                alt="tailwindIcon"
                width={100}
                height={100}
              />
            </div>
            <div
              title="Firestore"
              className="cursor-pointer basis-1/3 lg:basis-1/5 flex-1 my-5 py-4 text-center flex flex-col items-center shadow-lg rounded-xl dark:shadow-yellow-400"
            >
              <Image
                className="my-4 rounded-xl"
                src={firestore}
                alt="firestore"
                width={100}
                height={100}
              />
            </div>
          </div>
        </section>
        <section id="project" className="pb-20">
          <div className="mb-4">
            <h3 className="text-3xl font-burtons py-1 dark:text-white ">
              Professional Projects
            </h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

            <motion.div
              variants={fadeIn("right", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={WhiteOak}
                alt="WhiteOak"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://mf.whiteoakamc.com/" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2 transition-all duration-500 text-center">
                  Live
                </div>
              </a>
              {/* <a href='https://drive.google.com/file/d/1PeItrCScqH4HaVoPx1ZKcY37Ctfm4sru/view?usp=share_link' target='_blank'><div className='cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500'>Live</div></a> */}
              {/* <a
                href="https://github.com/Jatin123lodhi/insta-jatin-reels"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a> */}
            </motion.div>
            <motion.div
              variants={fadeIn("left", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={itcAMS}
                alt="itcAMS"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              {/* <a href="https://uat.upcapita.com/home" target="_blank"> */}
              <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2 transition-all duration-500 text-center">
                ITC-AMS
              </div>
              {/* </a> */}
              {/* <a href='https://drive.google.com/file/d/1PeItrCScqH4HaVoPx1ZKcY37Ctfm4sru/view?usp=share_link' target='_blank'><div className='cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500'>Live</div></a> */}
              {/* <a
                href="https://github.com/Jatin123lodhi/insta-jatin-reels"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a> */}
            </motion.div>
            <motion.div
              variants={fadeIn("right", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={UpCapita}
                alt="UpCapita"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://uat.upcapita.com/home" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2 transition-all duration-500 text-center">
                  Currently in UAT
                </div>
              </a>
              {/* <a href='https://drive.google.com/file/d/1PeItrCScqH4HaVoPx1ZKcY37Ctfm4sru/view?usp=share_link' target='_blank'><div className='cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500'>Live</div></a> */}
              {/* <a
                href="https://github.com/Jatin123lodhi/insta-jatin-reels"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a> */}
            </motion.div>
            <motion.div
              variants={fadeIn("left", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={SkFinance}
                alt="SkFinance"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://skfin.in/" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              {/* <a
                href="https://github.com/Jatin123lodhi/youtube-v1"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a> */}
            </motion.div>
            <motion.div
              variants={fadeIn("right", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={AltaBooking}
                alt="AltaBooking"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a href="https://www.altabooking.com/" target="_blank">
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              {/* <a
                href="https://github.com/Jatin123lodhi/NamasteReactJatin"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a> */}
            </motion.div>
            <motion.div
              variants={fadeIn("left", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={IndusIndBank}
                alt="IndusIndBank"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a
                href="https://indusnet.indusind.com/corp/BANKAWAY?Action.RetUser.Init.001=Y&AppSignonBankId=234&AppType=corporate&CorporateSignonLangId=001"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/2 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              {/* <a
                href="https://github.com/Jatin123lodhi/jatin-portfolio"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a> */}
            </motion.div>
          </div>
        </section>
        <section id="personal-project" className="pb-20">
          <div className="mb-4">
            <h3 className="text-3xl font-burtons py-1 dark:text-white ">
              Personal Projects
            </h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <motion.div
              variants={fadeIn("right", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={CryptoTracker}
                alt="CryptoTracker"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a
                href="https://netify-crypto-tracker.netlify.app/"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              {/* <a href='https://drive.google.com/file/d/1PeItrCScqH4HaVoPx1ZKcY37Ctfm4sru/view?usp=share_link' target='_blank'><div className='cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500'>Live</div></a> */}
              <a
                href="https://github.com/Subrata-99/react-crypto-tracker"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a>
            </motion.div>
            <motion.div
              variants={fadeIn("left", "0.3")}
              initial="hidden"
              whileInView="show"
              viewport={{ once: false, amount: "0.3" }}
              className="group relative overflow-hidden basis-1/3 flex-1  rounded-xl shadow-lg  dark:shadow-md dark:shadow-red-400"
            >
              <div className="group-hover:bg-black/70 w-full h-full absolute z-40 transition-all duration-300"></div>
              <Image
                src={ChatApp}
                alt="ChatApp"
                className="group-hover:scale-125 transition-all duration-500 rounded-xl   "
              />
              <a
                href="https://lets-connect-609751.netlify.app/chats"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-1/3 z-40 group-hover:bottom-1/2 transition-all duration-500">
                  Live
                </div>
              </a>
              <a
                href="https://github.com/Subrata-99/MERN-Chat-App-Let-s-Connect-"
                target="_blank"
              >
                <div className="cursor-pointer text-xl text-white absolute -bottom-full left-2/3 z-40 group-hover:bottom-1/2  transition-all duration-700">
                  Code{" "}
                </div>
              </a>
            </motion.div>
          </div>
        </section>
        <section>
          <div
            title="React"
            className="my-5 py-4 text-center shadow-lg rounded-xl  dark:shadow-red-400"
          >
            <h2 className="text-3xl py-2 text-red-700 font-medium md:text-3xl">
              {"< 🙏Because once a developer said🙏 />"}
            </h2>
            <h3 className="text-2xl font-mono p-10 md:text-3xl dark:text-white">
              <Typewriter
                options={{
                  strings: [
                    `"Software and Temples are much the same — first we build them then we pray"`,
                    `“It works on my machine.”`,
                    `“Time, Tide and Javascript waits for none.”`,
                    `“It's not a bug - it's an undocumented feature.”`,
                    `“Programming is like sex. One mistake and you have to support it for the rest of your life.”`,
                    `“If at first you don’t succeed; call it version 1.0”`,
                    `“Code never lies, comments sometimes do”`,
                  ],
                  autoStart: true,
                  loop: true,
                  deleteSpeed: 20,
                }}
              />
            </h3>
          </div>
        </section>
        <footer id="footer" className="pb-10 flex-col justify-center">
          <h1 className="text-xl text-center text-gray-600 font-medium dark:text-gray-400">
            No © copyright issues.
          </h1>
          <div className="flex-col items-center py-10">
            <p className="text-center  dark:text-gray-400">
              You can find me below
            </p>
            <div className="text-4xl flex justify-center gap-5 py-3 text-gray-600  dark:text-gray-300">
              <a href="mailto:dasbro9@gmail.com" target="_blank">
                <AiFillMail />
              </a>
              <a
                href="https://www.linkedin.com/in/subrata-das-77a6b91b1/"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Subrata-99" target="_blank">
                <AiFillGithub />
              </a>
            </div>
            <div className="text-center">
              <BsMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-xl dark:text-white "
              />
            </div>
          </div>
        </footer>
        {/* </section> */}
        <section>
          <nav className="fixed left-0 bottom-4 lg:bottom-8 w-full overflow-hidden z-50 ">
            <div className="mx-auto w-80 bg-black/10 h-12 backdrop-blur-sm rounded-3xl flex justify-between ">
              <Link
                to="home"
                smooth={true}
                activeClass="active"
                spy={true}
                className=" flex items-center px-2 mx-8 text-2xl cursor-pointer dark:border-white"
              >
                <FaHome className="dark:text-white" />
              </Link>
              <Link
                to="skill"
                smooth={true}
                activeClass="active"
                spy={true}
                className=" flex items-center px-2 mx-8 text-2xl cursor-pointer dark:border-white "
              >
                <FaTools className="dark:text-white" />
              </Link>
              <Link
                to="project"
                smooth={true}
                activeClass="active"
                spy={true}
                className=" flex items-center px-2 mx-8 text-2xl cursor-pointer dark:border-white"
              >
                <BsFillRocketTakeoffFill className="dark:text-white" />
              </Link>
            </div>
          </nav>
        </section>
      </main>
    </div>
  );
}
